name: Lint

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  golangci:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with: # BUG: typecheck error when enable all
          args: --disable-all -E goimports,misspell,whitespace
